name: ci

on:
  push:
    branches: [main]
  pull_request:

jobs:
  build_test:
    runs-on: macos-latest
    env:
      DOTNET_CLI_TELEMETRY_OPTOUT: "1"
      DOTNET_NOLOGO: "1"

    steps:
      - name: Checkout
        uses: actions/checkout@v4

      # Add this: ensure JDK 17 is used for the entire job
      - name: Set up Java 17
        uses: actions/setup-java@v4
        with:
          distribution: microsoft   # or 'temurin'
          java-version: '17.0.10'
          
      # Optional: confirm the JDK that will be used
      - name: Verify Java
        run: |
          echo "JAVA_HOME=$JAVA_HOME"
          java -version
          javac -version

      - name: Dotnet Workload Restore
        run: dotnet workload restore

      - name: Restore NuGet packages - Main App
        working-directory: ./PhysicallyFitPT
        run: dotnet restore PhysicallyFitPT.csproj --use-lock-file

      - name: Restore NuGet packages - Web App
        working-directory: ./PhysicallyFitPT.Web
        run: dotnet restore PhysicallyFitPT.Web.csproj --use-lock-file

      - name: Restore NuGet packages - Shared
        working-directory: ./PhysicallyFitPT.Shared
        run: dotnet restore PhysicallyFitPT.Shared.csproj --use-lock-file

      - name: Restore NuGet packages - Domain
        working-directory: ./PhysicallyFitPT.Domain
        run: dotnet restore PhysicallyFitPT.Domain.csproj --use-lock-file

      - name: Restore NuGet packages - Infrastructure
        working-directory: ./PhysicallyFitPT.Infrastructure
        run: dotnet restore PhysicallyFitPT.Infrastructure.csproj --use-lock-file

      - name: Restore NuGet packages - Seeder
        working-directory: ./PhysicallyFitPT.Seeder
        run: dotnet restore PhysicallyFitPT.Seeder.csproj --use-lock-file

      - name: Restore NuGet packages - Tests
        working-directory: ./PhysicallyFitPT.Tests
        run: dotnet restore PhysicallyFitPT.Tests.csproj --use-lock-file

      - name: Setup .NET SDK 8.0.403 (with NuGet cache)
        uses: actions/setup-dotnet@v4
        with:
          dotnet-version: "8.0.403"
          cache: true
          cache-dependency-path: '**/packages.lock.json'
          
      - name: Show .NET info
        run: dotnet --info

      - name: Install MAUI workload
        run: dotnet workload install maui
      


      - name: Enforce Code Formatting
        run: |
          dotnet tool update -g dotnet-format || dotnet tool install -g dotnet-format
          dotnet format --verify-no-changes --no-restore

      - name: Prepare artifacts directory
        run: mkdir -p artifacts

      - name: Build Android (Release)
        run: dotnet build ./PhysicallyFitPT/PhysicallyFitPT.csproj -c Release -f net8.0-android -bl:artifacts/build-android.binlog

      - name: Build iOS (Release)
        run: dotnet build ./PhysicallyFitPT/PhysicallyFitPT.csproj -c Release -f net8.0-ios -bl:artifacts/build-ios.binlog

      - name: Build Web (Release)
        run: dotnet build ./PhysicallyFitPT.Web/PhysicallyFitPT.Web.csproj -c Release -bl:artifacts/build-web.binlog

      - name: Test (unit tests only)
        run: dotnet test ./PhysicallyFitPT.Tests/PhysicallyFitPT.Tests.csproj -c Release --logger "trx;LogFileName=artifacts/test-results.trx"

      - name: Upload build/test artifacts
        if: always()
        uses: actions/upload-artifact@v4
        with:
          name: ci-artifacts
          path: |
            artifacts/**
