name: Copilot Auto-Fix CI Failures

on:
  repository_dispatch:
    types: [copilot-auto-fix]

permissions:
  contents: write
  pull-requests: write
  issues: write

jobs:
  auto-fix:
    name: Auto-Fix CI Failures
    runs-on: ubuntu-latest
    steps:
      - name: Process auto-fix request
        uses: actions/github-script@v7
        with:
          github-token: ${{ secrets.GITHUB_TOKEN }}
          script: |
            const owner = context.repo.owner;
            const repo = context.repo.repo;
            const payload = context.payload.client_payload;
            
            console.log('Copilot auto-fix triggered with payload:', JSON.stringify(payload, null, 2));
            
            const pr_number = payload.pr_number;
            const run_id = payload.run_id;
            const failed_jobs = payload.failed_jobs || [];
            
            // Post acknowledgment that Copilot is starting to work
            const acknowledgment = [
              '🤖 **Copilot Auto-Fix Activated**',
              '',
              `✅ Copilot has been automatically triggered to analyze and fix CI failures from [workflow run ${run_id}](https://github.com/${owner}/${repo}/actions/runs/${run_id}).`,
              '',
              '**Failed Jobs Being Analyzed:**',
              ...failed_jobs.map(job => `- [${job.name}](${job.html_url}) (${job.conclusion})`),
              '',
              '**Next Steps:**',
              '- Copilot will analyze the failures and create fixes',
              '- Code changes will be committed automatically',
              '- CI will re-run to validate fixes',
              '',
              '*This is an automated response. Copilot is now working on the issues.*'
            ];
            
            await github.rest.issues.createComment({
              owner,
              repo,
              issue_number: pr_number,
              body: acknowledgment.join('\n')
            });
            
            // Create a detailed issue for Copilot to work on
            const issueTitle = `[AUTO] CI Failures in PR #${pr_number} - Copilot Fix Required`;
            const issueBody = [
              '## Automatic CI Failure Report',
              '',
              `This issue was automatically created due to CI failures in PR #${pr_number}.`,
              '',
              `**Workflow Run:** https://github.com/${owner}/${repo}/actions/runs/${run_id}`,
              '',
              '**Failed Jobs:**',
              ...failed_jobs.map(job => `- **${job.name}**: ${job.conclusion} - [View logs](${job.html_url})`),
              '',
              '## Expected Actions',
              '',
              '1. Analyze the failed CI jobs and their logs',
              '2. Identify the root cause of each failure',
              '3. Implement minimal fixes to resolve the issues',
              '4. Commit changes and validate CI passes',
              '',
              '## CI Pipeline Requirements',
              '',
              '- **format-check**: StyleCop formatting verification',
              '- **analyze**: Roslynator static analysis (0 diagnostics)',
              '- **build**: Cross-platform MAUI builds',
              '- **test**: Unit test execution',
              '',
              `**Related PR:** #${pr_number}`,
              '',
              '*This issue will be automatically closed when CI passes.*'
            ];
            
            try {
              const issue = await github.rest.issues.create({
                owner,
                repo,
                title: issueTitle,
                body: issueBody.join('\n'),
                labels: ['automated', 'ci-failure', 'copilot-fix'],
                assignees: ['copilot']
              });
              
              console.log(`Created auto-fix issue: ${issue.data.html_url}`);
              
              // Reference the issue in the PR
              await github.rest.issues.createComment({
                owner,
                repo,
                issue_number: pr_number,
                body: `📋 **Auto-Fix Issue Created:** ${issue.data.html_url}\n\nCopilot will track progress and fixes in the linked issue.`
              });
              
            } catch (error) {
              console.log('Could not create auto-fix issue:', error.message);
            }