name: Auto-format PR

on:
  pull_request:
    types: [opened, synchronize, reopened]

permissions:
  contents: write
  pull-requests: write

jobs:
  autoformat:
    name: Auto-format Code
    runs-on: ubuntu-latest
    if: github.event.pull_request.head.repo.full_name == github.repository
    
    steps:
      - name: Checkout PR
        uses: actions/checkout@v4
        with:
          token: ${{ secrets.GITHUB_TOKEN }}
          ref: ${{ github.event.pull_request.head.ref }}
          fetch-depth: 0
      
      - name: Setup .NET SDK 8.0.x
        uses: actions/setup-dotnet@v4
        with:
          dotnet-version: "8.0.x"
          cache: true
          cache-dependency-path: '**/packages.lock.json'
      
      - name: Cache NuGet packages
        uses: actions/cache@v4
        with:
          path: ~/.nuget/packages
          key: ${{ runner.os }}-nuget-${{ hashFiles('**/packages.lock.json') }}
          restore-keys: |
            ${{ runner.os }}-nuget-
      
      - name: Restore Ubuntu-compatible projects
        run: |
          # Restore projects that can be formatted on Ubuntu (no mobile dependencies)
          dotnet restore src/PhysicallyFitPT.Core/PhysicallyFitPT.Core.csproj --use-lock-file
          dotnet restore src/PhysicallyFitPT.Web/PhysicallyFitPT.Web.csproj --use-lock-file
          dotnet restore src/PhysicallyFitPT.Infrastructure/PhysicallyFitPT.Infrastructure.csproj --use-lock-file
          dotnet restore src/PhysicallyFitPT.Shared/PhysicallyFitPT.Shared.csproj --use-lock-file
          
          # Also restore test and seeder projects if they exist
          [ -f tests/PhysicallyFitPT.Core.Tests/PhysicallyFitPT.Core.Tests.csproj ] && dotnet restore tests/PhysicallyFitPT.Core.Tests/PhysicallyFitPT.Core.Tests.csproj --use-lock-file || true
          [ -f src/PhysicallyFitPT.Seeder/PhysicallyFitPT.Seeder.csproj ] && dotnet restore src/PhysicallyFitPT.Seeder/PhysicallyFitPT.Seeder.csproj --use-lock-file || true
      
      - name: Check for formatting issues
        id: format-check
        run: |
          echo "Checking format for Ubuntu-compatible projects (excluding MAUI)..."
          
          HAS_CHANGES=false
          FORMAT_OUTPUT=""
          
          # Format Ubuntu-compatible projects individually
          projects=(
            "./src/PhysicallyFitPT.Core/PhysicallyFitPT.Core.csproj"
            "./src/PhysicallyFitPT.Web/PhysicallyFitPT.Web.csproj"
            "./src/PhysicallyFitPT.Infrastructure/PhysicallyFitPT.Infrastructure.csproj"  
            "./src/PhysicallyFitPT.Shared/PhysicallyFitPT.Shared.csproj"
          )
          
          # Add test and seeder projects if they exist
          [ -f "./tests/PhysicallyFitPT.Core.Tests/PhysicallyFitPT.Core.Tests.csproj" ] && projects+=("./tests/PhysicallyFitPT.Core.Tests/PhysicallyFitPT.Core.Tests.csproj")
          [ -f "./src/PhysicallyFitPT.Seeder/PhysicallyFitPT.Seeder.csproj" ] && projects+=("./src/PhysicallyFitPT.Seeder/PhysicallyFitPT.Seeder.csproj")
          
          for project in "${projects[@]}"; do
            if [ -f "$project" ]; then
              echo "Checking format for $project..."
              if ! dotnet format "$project" --verify-no-changes --verbosity diagnostic; then
                echo "Formatting needed for $project"
                HAS_CHANGES=true
              fi
            fi
          done
          
          if [ "$HAS_CHANGES" = true ]; then
            echo "FORMAT_NEEDED=true" >> $GITHUB_OUTPUT
          fi
      
      - name: Apply formatting fixes
        if: steps.format-check.outputs.FORMAT_NEEDED == 'true'
        run: |
          echo "🔧 Applying code formatting fixes..."
          
          # Apply formatting to Ubuntu-compatible projects
          projects=(
            "./src/PhysicallyFitPT.Core/PhysicallyFitPT.Core.csproj"
            "./src/PhysicallyFitPT.Web/PhysicallyFitPT.Web.csproj"
            "./src/PhysicallyFitPT.Infrastructure/PhysicallyFitPT.Infrastructure.csproj"
            "./src/PhysicallyFitPT.Shared/PhysicallyFitPT.Shared.csproj"
          )
          
          # Add test and seeder projects if they exist
          [ -f "./tests/PhysicallyFitPT.Core.Tests/PhysicallyFitPT.Core.Tests.csproj" ] && projects+=("./tests/PhysicallyFitPT.Core.Tests/PhysicallyFitPT.Core.Tests.csproj")
          [ -f "./src/PhysicallyFitPT.Seeder/PhysicallyFitPT.Seeder.csproj" ] && projects+=("./src/PhysicallyFitPT.Seeder/PhysicallyFitPT.Seeder.csproj")
          
          for project in "${projects[@]}"; do
            if [ -f "$project" ]; then
              echo "Formatting $project..."
              dotnet format "$project" --verbosity diagnostic
            fi
          done
          
          # Check if any files were modified
          if git diff --quiet; then
            echo "No formatting changes needed"
            echo "FORMAT_APPLIED=false" >> $GITHUB_ENV
          else
            echo "Formatting changes applied"
            echo "FORMAT_APPLIED=true" >> $GITHUB_ENV
          fi

      - name: Commit formatting changes
        if: env.FORMAT_APPLIED == 'true'
        run: |
          git config --local user.email "action@github.com"
          git config --local user.name "Auto-format Bot"
          git add -A
          git commit -m "Auto-format: Apply StyleCop formatting rules

          - Applied dotnet format to Ubuntu-compatible projects
          - Fixed indentation, spacing, and style issues  
          - Automated by GitHub Actions on PR #${{ github.event.pull_request.number }}
          
          Note: MAUI projects require macOS runner and are formatted during CI"
          git push
      
      - name: Comment on PR with formatting results
        if: steps.format-check.outputs.FORMAT_NEEDED == 'true'
        uses: actions/github-script@v7
        with:
          github-token: ${{ secrets.GITHUB_TOKEN }}
          script: |
            const formatApplied = process.env.FORMAT_APPLIED === 'true';
            
            const comment = formatApplied ? 
              `🔧 **Auto-formatting applied!**
              
              I've automatically applied code formatting fixes to this PR to ensure consistency with PFPT coding standards.
              
              **Changes applied to Ubuntu-compatible projects:**
              - StyleCop formatting rules
              - Consistent indentation and spacing
              - Code style standardization
              
              **Projects formatted:**
              - ✅ PhysicallyFitPT.Core
              - ✅ PhysicallyFitPT.Web  
              - ✅ PhysicallyFitPT.Infrastructure
              - ✅ PhysicallyFitPT.Shared
              - ✅ Test and Seeder projects (if present)
              
              **Note:** MAUI projects require macOS runner and will be formatted during the main CI workflow.
              
              The PR is now ready for review with properly formatted code.` :
              
              `⚠️ **Formatting issues detected**
              
              Code formatting issues were found but could not be automatically fixed.
              
              Please run \`dotnet format\` on the affected projects locally and commit the changes.
              
              **Note:** This auto-formatter only handles Ubuntu-compatible projects. MAUI projects are formatted during the main CI workflow on macOS.`;
            
            await github.rest.issues.createComment({
              owner: context.repo.owner,
              repo: context.repo.repo,
              issue_number: context.issue.number,
              body: comment
            });